# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    strategy:
      matrix:
        platform:
          - os: ubuntu-latest
            name: linux
            arch: x64
          # Still in preview, need specific version
          - os: ubuntu-24.04-arm
            name: linux
            arch: arm64
          - os: windows-latest
            name: windows
            arch: x64

    runs-on: ${{ matrix.platform.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: go build -o ./build/ -v ./...

    - name: Test
      run: go test -v ./...

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: matrix-tools-${{ matrix.platform.name }}-${{ matrix.platform.arch }}
        path: build/*
        retention-days: 30
